spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://192.168.1.105:1433;DatabaseName=Y8_MES15;sendStringParametersAsUnicode=false
          username: sa
          password: root
          initialSize: 5
          minIdle: 5
          maxActive: 20
        erp:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://192.168.1.44:1433;DatabaseName=DB_JDDZ
          username: sa
          password: 1
          initialSize: 5
          minIdle: 5
          maxActive: 20


#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.1.105:1433;DatabaseName=Y8_MES15
#    username: sa
#    password: root
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20

  jackson:
    time-zone: GMT+8

server:
  port: 8080


mybatis-plus:
  mapper-locations: mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
