spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.1.105:1433;DatabaseName=Y8_MES15
    username: sa
    password: root

    # 使用Druid数据源  配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    name: bird
    # 监控Druid数据源统计 监控统计:stat  日志监控:log4j、slf4j  防御SQL注入:wall
    filters: stat
    # 初始化连接
    initial-size: 2
    # 最大空闲连接数
    max-idle: 10
    # 最小空闲连接数
    min-idle: 1
    # 获取连接超时的等待时间 60s
    max-wait: 60000
    # 最大的活动连接
    max-active: 20
    # 间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    # 一个连接在连接池中最小生存的空间
    min-evictable-time-millis: 300000
    # 验证连接有效与否的sql语句
    validation-query: SELECT 'x'
    # 指明连接是否被空闲连接回收器 (如果有)进行检验。如果监测失败，则连接将被连接池中去除
    test-while-idle: true
    # 借出连接时不要测试，否则影响性能
    test-on-borrow: false

  jackson:
    time-zone: GMT+8

server:
  port: 8080


mybatis-plus:
  mapper-locations: mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
